### ISSUE TITLE
Safe topological modification

### ISSUE THREAD

**Issue by untereiner** [cgogn/CGoGN_2#116]
Hier, je n'ai pas eut le temps de finir ma question concernant les algorithmes de changement topo qui agissent sur toute la carte.
Comment procède-t-on ?
- Est-ce qu'on sauvegarde dans un coin les brins des cellules puis on fait l'opération topo ?
- Est-ce qu'on la fait à la volé dans une lambda ? (quid de l'arrêt ?)

Bref, peut-on se donner des règles ?

**Comment by pierrekraemer** [comment]
Les parcours globaux récupèrent l'itérateur de fin avant de commencer le parcours. La terminaison du parcours n'est donc a priori pas un problème. En revanche, rien ne nous dit que les nouveaux éléments ajoutés ne vont pas se nicher au milieu des éléments qui existaient (trous dans les conteneurs).
On peut résoudre ça soit :
- en gérant soi-même un marqueur sur les éléments ajoutés pour ne pas les traiter si on les rencontre -> lourd et pénible à écrire
- en limitant les parcours globaux à de la lecture seule et en récupérant donc d'abord l'ensemble des cellules à traiter avant de parcourir cet ensemble pour les traiter
- en proposant une méthode du genre "foreach_existing_cell" qui encapsule la proposition précédente en gérant elle-même l'ensemble de cellules extraites avant d'y appliquer la fonction; ce parcours pourrait d'ailleurs recevoir également un Mask pour sélectionner les cellules à considérer.

D'ailleurs plus je pense aux Mask, plus je me dis que leur version qui fait uniquement de la sélection devraient être passés sous la forme d'une lambda qui prend un brin (ou une cellule) et renvoie un booléen plutôt que d'un objet contenant une méthode de validation.

**Comment by untereiner** [comment]
Je réactive juste se sujet pour essayer d'avoir un truc propre et clair sur les parcours globaux modifiant la topo. Est-ce que l'on peut envisager un mask qui met en cache avant d'appliquer la modifs ? Est-ce qu'on fournit un "foreach_existing_cell" ? 

En fait est qu'il ne devrait pas y avoir une façon de parcourir la carte en lecture et une autre en écriture ?

**Comment by pierrekraemer** [comment]
Les parcours globaux ne sont toujours safe qu'en lecture. Même si on sauve les éléments à parcourir avant le parcours, si on fait des suppression en cours de route, on passera par des éléments qui n'existent plus..
Si on souhaite parcourir l'ensemble des cellules existantes, les CellCache me semblent suffisamment simple à utiliser :

``` c++
using Map = CMap2<DefaultMapTraits>;
using Vertex = typename Map::Vertex;

Map map;
CellCache<Map> cache(map);
...
c.build<Vertex>();
map.foreach_cell([&] (Vertex v)
{
  // do something with existing vertex
}, cache);
```

**Comment by pierrekraemer** [comment]
D'ailleurs je vais proposer d'ici peu une PR qui va tenter de clarifier un peu les notions de Mask, filtre, cache, etc..
-> #183
