### ISSUE TITLE
submodules

### ISSUE THREAD

**Issue by untereiner** [cgogn/CGoGN_2#122]
Hi guys,

Je suis tombé par hasard sur la notion de [sous-modules git](https://git-scm.com/book/fr/v2/Utilitaires-Git-Sous-modules). Comme tous les projets google (google-{test, mock, bench}) sont sous git on pourrait utiliser cette fonctionnalité pour éviter d'alourdir notre dépôt avec ces third-parties.
Qu'en pensez-vous ?

**Comment by untereiner** [comment]
On peut même faire un sous-module pour [eigen](https://github.com/RLovelett/eigen).

**Comment by sylvainthery** [comment]
J'y voit le même défaut que les super-build, c.a.d que l'on ne maitrise plus complétement la version courante
Et ça n' pas l'air pratique, car un clone du repo, ne clone pas les sous-modules, il faut le faire explicitement pour chacun, pas très pratique.

**Comment by untereiner** [comment]
Ton sous module peut tracker une branche ou un [commit spécifique](http://stackoverflow.com/a/18797720). Du coup tu maîtrise la version courante de tes libs externes et en plus tu peux gérer directement, via git, la mise à jour de ces sous-modules. D'accord pour le clone qui ne récupère "pas tout". En même temps, est-ce que tout le monde veux récupérer google test pour essayer cgogn ?

**Comment by sylvainthery** [comment]
En fait tous les sous modules sont mis à jour en même temps, il y a 2 commandes à faire:
- git submodule init
- git submodule update

On peut faire ça automatiquement dans le cmake (https://github.com/xdbr/cmake-module-submodule.cmake)
Reste à voir si c'est pertinent.

Le défaut que je vois, c'est que l'archive que tu peux récupérer depuis git-hub ne contient plus tout ce qu'il faut pour compiler.

**Comment by untereiner** [comment]
ok, on ne peut effectivement pas récupérer les sous modules lorsqu'on télécharge le projet sous la forme d'une archive à partir du bouton "download zip". Je propose dans un premier temps de gérer en sous module les trucs de tests et de bench qui ne sont pas nécessaire à l'utilisateur moyen.

**Comment by sylvainthery** [comment]
Les google_bidules ;)

**Comment by untereiner** [comment]
@pierrekraemer un avis ?

**Comment by pierrekraemer** [comment]
Pas vraiment..
Je suis d'accord que les google_bidules ne sont pas forcément utiles à tout le monde et qu'on pourrait cloner ou télécharger le dépôt sans les récupérer.
En même temps, il faudrait alors que lorsque l'on fait un truc du genre "make tests" pour la première fois, on récupère automatiquement tout ce qu'il faut. Je ne sais pas si on peut le faire ni si c'est facile (j'intuite que non..).
La solution simple reste de laisser toutes ces libs dans le dépôt (est-ce que c'est très lourd ?) et de générer un Makefile par défaut qui ne compile que CGoGN.
Si on veut juste ne pas alourdir le clonage de notre dépôt mais quand même récupérer automatiquement ces dépendances alors il faut que CMake les récupère (est-ce qu'on peut préciser quel commit on veut récupérer quand c'est CMake qui clone un dépôt ?).
Bref, je suis pas très clair, mais je ne sais pas exactement ce qu'on peut faire et ce qui est pertinent de faire..
