### ISSUE TITLE
define uint32 as cgogn local type

### ISSUE THREAD

**Issue by sylvainthery** [cgogn/CGoGN_2#153]
unsigned int ça saoule:
- deux mots séparés par un espace: plein de pb
- c'est long a écrire
- ça prend de la place

Proposition:
- using uint32 = std::uint32_t; (dans le namespace cgogn)

Ca permet de remplacer static_cast<unsigned int>(x) par uint32(x);

**Comment by sylvainthery** [comment]
Ou alors on utilise directement **uint32_t** sans le std:: qui semble passer à la compil.

**Comment by untereiner** [comment]
Ok, ça me convient. Mais il faut être homogène alors!

```
using  int8 = std::int8_t;
using  int16 = std::int16_t;
using  int32 = std::int32_t;
using  int64 = std::int64_t;

using  uint8 = std::uint8_t;
using  uint16 = std::uint16_t;
using  uint32 = std::uint32_t;
using  uint64 = std::uint64_t;

using float32 = float;
using float64 = double;
```

avec namespace numeric dans lequel on peut mettre des fonctions du style:
scale(x, a, b)
clamp() etc...

**Comment by untereiner** [comment]
J'en profiterai bien pour enlever le postfix "Handler" dans CellAttributeHandler... C'est long à écrire, surtout quand tu te tapes "typename MAP::template" devant...

**Comment by pierrekraemer** [comment]
Je suis bien d'accord avec le fait d'enlever le "Handler" dans ces noms de types.
Mais on pourrait faire ça dans des contributions séparées.

**Comment by untereiner** [comment]
oui je profitais juste de l'occasion d'un thread actif :wheelchair:
