### ISSUE TITLE
CMakeLists: liste de fichiers

### ISSUE THREAD

**Issue by pierrekraemer** [cgogn/CGoGN_2#17]
Dans le CMakeLists de cgogn/core, il y a une liste exhaustive des fichiers header et source. Y aurait-il un quelconque désavantage à remplacer cela par un GLOB quelque chose pour ne pas avoir à maintenir cette liste à jour ?
Par example, les nouveaux fichiers assert.h et assert.cpp ne sont pas listés dedans et n'apparaissent pas dans l'arborescence du projet dans QTCreator.
De même, le dossier utils ne contient pas du tout de CMakeLists pour le moment et n'apparait pas non plus dans QTCreator.

**Comment by untereiner** [comment]
J'ai effectivement oublié de rajouter le CMakeList dans mon commit...
Je vais le rajouter.
Pourquoi il y a un chunk_array.cpp avec rien dedans ?

**Comment by untereiner** [comment]
En passant, la manière dont on fait les includes gards n'est pas conforme à la norme: http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

J'ai des warnings avec clang...

Je serai d'avis de mettre : PATH_TO_FILE_MYFILE_

**Comment by pierrekraemer** [comment]
Mais est-ce que ça vous convient de maintenir une liste de fichier dans les CMakeLists ?
On ne préfère pas une solution à base de RegExp ?

**Comment by etienneschmitt** [comment]
Je sais plus pourquoi dans SOFA les gens continuent de les spécifier à la main. Il me semble qu'à un certain moment certains IDEs n'affichaient pas forcément tous les fichiers en utilisant les regex. je ne sais plus sur quel OS.
Bref, pas mal de flou, je vais tester sous windows ce qui se passe avec les regex.
E.

**Comment by sylvainthery** [comment]
Le cpp avec rien dedans c'est juste que comme il n'y avait que des .h il fallait un cpp
pour qu'il compile la lib, sinon pas de target !
