### ISSUE TITLE
functions naming convention

### ISSUE THREAD

**Issue by untereiner** [cgogn/CGoGN_2#27]
Vous allez rire mais j'ai encore une suggestion esthétique...
En lisant le code je trouve qu'on gagnerait à adopter une convention de nommage similaire à celle de la stl pour les noms de fonction.
Là, j'ai l'impression de lire du java mélangé à quelque chose d'autre.
Par exemple la fonction:

```
void addChunk() override
{
    table_data_.emplace_back(new T[CHUNKSIZE]());
}
```

deviendrait:

```
void add_chunk() override
{
    table_data_.emplace_back(new T[CHUNKSIZE]());
}
```

PS: d'ailleurs pourquoi addChunk ? On peut faire "add" d'autre chose dans la classe ChunkArray ?
PS2: d'ailleurs le nom add_back serait plus clair non ?

**Comment by pierrekraemer** [comment]
Tout à fait d'accord avec le "snake case" à la place du "camel case".
J'ai déjà commencé pas mal avec les noms des membres et des paramètres, mais pas encore les noms des méthodes.

**Comment by sylvainthery** [comment]
Il faut se mettre d'accord rapidement, plus on attend plus ça  sera pénible de changer
Si tout le monde est ok on part sur:
- membres: snake case suivi de "_" (table_attrib_)
- methodes, param. & variables: snake case ( add_chunk(), ... )
- classes + typedef : camel case (ChunkArray)
- param template: majuscule (CHUNKSIZE)
- namespace: minuscule (cgogn::)
- nom de fichier: snake case (chunk_array.h)

**Comment by untereiner** [comment]
J'imagine que pour les membres tu voulais écrire "suivi de _" (table_attrib_)
Cela me convient parfaitement!

**Comment by sylvainthery** [comment]
A le  site de m... il vire les underscore qui ne sont pas entre deux caractères !!
pour écrire: membres: snake case suivi de "_" (table_attrib_) 
il faut taper \_

**Comment by untereiner** [comment]
Qui s'en charge ? (il faudrait friser le temps de le faire)

**Comment by pierrekraemer** [comment]
C'est fait :-)
