### ISSUE TITLE
le probléme de paralléle

### ISSUE THREAD

**Issue by hananfirdaws** [cgogn/CGoGN_2#288]
Bonjour
Je me nomme Hakem et je me prénomme Hanen. Je suis étudiante à l'université l’Arbi Ben M’hidi Oum El Bouaghi (Algerie). Je suis en Master 2 informatique option Architecture distribuée. Le thème de mon mémoire de fin d'étude s’intitule : Utilisation de la librairie CGOGN pour le développement d’un modèle topologique parallèle.
 Je vous contacte dans l'espoir d'obtenir votre aide, j’ai déjà lus tous les classes de la librairie CGOGN mais je n'ai pas compris la méthodologie du parallélisme, et la classe ThreadFunctor et je n'ai pas pu détecter s'il y'a un problème au niveau de cette librairie ou il n'existe plus.
Merci et bien cordialement.

**Comment by pierrekraemer** [comment]
Il n'y a pas de classe ThreadFunctor dans CGoGN_2.
On peut parcourir les cellules en parallèle en utilisant la méthode intitulée parallel_foreach_cell. Cette méthode reçoit en paramètre une lambda expression à exécuter sur chaque cellule parcourue ainsi que l'index du thread qui effectue ce traitement. Le nombre de threads utilisés dépend du nombre de coeurs de l'architecture sous-jacente. Il n'y a pas de problème particulier avec cette méthode.

**Comment by hananfirdaws** [comment]
merci infiniment de m'avoir répondu 
je suis tout à fait d'accord avec vous ce n'est  pas la classe ThreadFunctor c'est plutot la classe ThreadFunction
cordialement

**Comment by pierrekraemer** [comment]
Dans CGoGN_2, il n'y a pas plus de classe ThreadFunction que de classe ThreadFunctor.

**Comment by hananfirdaws** [comment]
je veux bien développer un aspect dans le parallélisme de cette librairie mais  je n'ai pas bien compris quelle est la méthode à suivre 
1. La première :  - Division des points en N groupes
                           - Affectation de change groupes à N GPU
                           - Assemblage de N objets                                            
2.La deuxième : - D'abords donner aux points des informations de voisinage
                          - Résoudre les conflits 
                          - Modélisation 
cordialement .

**Comment by pierrekraemer** [comment]
La méthode parallel_foreach_cell affecte des cellules à traiter à chacun des threads disponibles (selon le nombre de coeurs du processeur). Si on a 4 coeurs, les cellules seront divisées en 4 paquets traités en parallèle par chacun des coeurs. La fonction de traitement passée en paramètre à parallel_foreach_cell reçoit l'index du thread qui traite la cellule, ce qui permet si on le souhaite d'accumuler une valeur pour chaque thread avant de réunir le tout à la fin.
Par exemple, si on voulait compter le nombre de sommets dont la composante X de l'attribut position est inférieure à 0, on pourrait écrire :
```c++
std::vector<uint32> nb_per_thread(cgogn::nb_threads());
map.parallel_foreach_cell([&] (CMap2::Vertex v, uint32 thread_index)
{
  if (position[v][0] < 0)
    nb_per_thread[thread_index]++;
});
uint32 total = 0;
for (uint32 nb : nb_per_thread)
  total += nb;
```

**Comment by hananfirdaws** [comment]
lorsque les threads terminent leurs traitements on peut fusionner ces cellules dans un volume 
quelle est la fonction qui effectue cette opération et est ce qu'il existe un problème dans cette fonction ?
cordialement

**Comment by pierrekraemer** [comment]
Je ne comprends pas ce que vous voulez dire par "on peut fusionner ces cellules dans un volume" ?

**Comment by hananfirdaws** [comment]
Je vous remercie beaucoup pour votre aide et  je souhaite que vous m'aider aussi
je veut dit  "merge these cells" , et j'espère que vous pouvez expliquer à moi la structure de données
 des markers et leurs relations avec le parallélisme 
merci infiniment pour vous

**Comment by pierrekraemer** [comment]
Fusionner les cellules serait une opération topologique qui supprimerait un ensemble de cellules existantes. Cela n'a pas de rapport avec le parcours parallèle des cellules.
Les markers sont en réalité des attributs booléens stockés dans le container de brins (pour les DartMarkers) ou dans les containers d'attributs (pour les CellMarkers). Chaque attribut booléen est indépendant et donc plusieurs Markers peuvent être utilisés en parallèle dans des threads différents. Pour des raisons d'efficacité, les attributs booléens sont conservés après leur utilisation et ré-utilisés lors des besoins ultérieurs (re-création d'un DartMarker ou d'un CellMarker).

**Comment by hananfirdaws** [comment]
merci pour votre aide
cordialement

**Comment by hananfirdaws** [comment]
Bonsoir 
lorsque un brin est marqué/démarqué la valeur de brin correspondant dans le vecteur (AttributeMultiVector ) est vrai/faux et quand un brin est marqué dans une partie envoyée au processeur 1, sera-t-il marqué aussi dans la seconde partie envoyée a processeur 2 
en cas de parallélisme. Quelle est la logique utilisé  pour y remédier  ?
merci pour vous

**Comment by pierrekraemer** [comment]
Dans CGoGN_2, la classe qui stocke les données ne s'appelle plus AttributeMultiVector mais ChunkArray.
Les DartMarkers et CellMarkers alloués au sein d'un thread utilisent des attributs booléens dédiés qui ne sont accédés chacun que depuis le thread correspondant. C'est ce qui permet d'éviter les conflits d'écriture dans les Markers. Les attributs booléens de marquage ne sont donc pas partagés entre les threads.
Lors d'un appel à `parallel_foreach_cell`, le thread principal parcourt les cellules (avec un Marker) puis affecte des paquets de cellules aux autres threads pour effectuer le traitement voulu. Les éventuels Markers utilisés au sein du traitement par chacun de ces threads sont alors propres à chaque thread. Le parcours parallèle des cellules garantit que chaque thread travaille sur des ensembles de cellules disjoints. Ainsi chaque thread peut lire et écrire dans des attributs de cellules sans risquer de conflit.

**Comment by hananfirdaws** [comment]
Salut 
Pour CGoGN_2 ,j'ai essayer d’exécuter les test pour comprendre le fonctionnement de cette librairie et la comparaison entre CGoGN et CGoGN_2 ,j'ai exécuter le test bench_multithreading mais il affiche un message d'erreur "terminate called after throwing an instance of 'std::regex_error'
what():  regex_error "
Est ce que vous pouvez m'aider pour résoudre ce probléme ?
merci pour vous
