### ISSUE TITLE
lambdas marquées comme "mutable"

### ISSUE THREAD

**Issue by etienneschmitt** [cgogn/CGoGN_2#57]
salut,
le cpp11 permet d'ajouter l'attribut "mutable" à une lambda. En gros son opérateur () ne sera pas const, contrairement au cas général.
Avec ces lambdas on a 2 pb : 
- les function_traits ne fonctionnent plus. C'est un faux pb qui se résout en copiant la spécialisation et en enlevant "const".
- beaucoup de méthodes foreach_\* qui sont const et qui appellent la lambda ne fonctionnent plus.

Pensez-vous qu'il faille dupliquer ces fonctions en créant leurs équivalents non-const ?
Ou qu'on proscrit l'utilisation de l'attribut "mutable" dans les lambdas ? 

a+,
E.

**Comment by pierrekraemer** [comment]
D'après ce que je vois : "mutable - allows body to modify the parameters captured by copy, and to call their non-const member functions"
Pourquoi est-ce restreint aux paramètres capturés par copie (et non par référence) ?

Sinon dans le code ci-dessous extrait de cmap2.h :

``` c++
template <Orbit ORBIT>
inline void init_orbit_embedding(Cell<ORBIT> c, unsigned int emb)
{
    foreach_dart_of_orbit(c, [this, emb] (Dart d) { this->template init_embedding<ORBIT>(d, emb); });
}
```

foreach_dart_of_orbit est const, appelle la lambda reçue en paramètre, cette lambda capture "this" par copie et appelle init_embedding qui n'est pas const. Et ça fonctionne, alors qu'apparemment ça ne devrait pas..
Une explication ?

**Comment by etienneschmitt** [comment]
ça fonctionne parce que ta méthode init_orbit_embedding n'est pas const, du coup "this" non plus.
Comme mutable n'est pas spécifié, la lambda prend un 'Map\* const'. Elle a tout a fait le droit d'appeler ce qu'elle veut dessus.
Par contre avec init_orbit_embedding en const, le code ne compilerait plus je pense (puisque la lambda aurait comme argument une Map const \* const sans mutable et une Map const \* avec mutable.

**Comment by cgogn** [comment]
Peux tu d'écrire un cas concret d'utilisation qui nécessite que () ne soit
pas construire ?
Le 20 déc. 2015 14:39, "Etienne Schmitt" notifications@github.com a
écrit :

**Comment by etienneschmitt** [comment]
Fixed in PR #283.

**Comment by hakou-dz** [comment]
salut
