### ISSUE TITLE
Boundary management

### ISSUE THREAD

**Issue by untereiner** [cgogn/CGoGN_2#79]
Find a way to manage the 2D and 3D boundary

**Comment by untereiner** [comment]
En dimension 3 c'est intéressant de parcourir le bord de manière efficace et à la manière d'une 2-carte. Est-ce que l'on peut envisager stocker directement les brins du bord dans un container à part entier ? On le traite de toute manière un peu à part déjà.

**Comment by untereiner** [comment]
oh esprits de l'internet je vous invoque @pierrekraemer et @david-cazier
Un avis ?

**Comment by pierrekraemer** [comment]
On a commencé à y refléchir avec Sylvain hier.
On propose de faire une réunion de vive voix à ce sujet. On se planifie ça bientôt ?

**Comment by untereiner** [comment]
semaine prochaine ? lundi/mardi/mercredi ?

**Comment by pierrekraemer** [comment]
Mercredi matin ? 9h ?

**Comment by david-cazier** [comment]
Ca marche

_--_
_David Cazier_
Professeur à l'université de Strasbourg - Laboratoire ICube
Equipe projet INRIA MIMESIS

2016-01-27 12:10 GMT+01:00 Pierre Kraemer notifications@github.com:

**Comment by untereiner** [comment]
Je viens penser qu'il faudrait un mécanisme similaire au `topo_cache` pour tester si une cellule est du bord. Notamment pour accélérer certains algorithmes des 3-cartes. Un `boundary_cache`, avec les mêmes contraintes que l'autre.

Un truc du style

```
template <Orbit ORBIT, BoundaryStrategy STRATEGY = BoundaryStrategy::AUTO>
inline bool is_boundary(Cell<ORBIT> c) const
{
   switch (STRATEGY)
  {
        case CACHE:
            return boundary_cache[c]; break;
       case 
          fforeach_dart_of_orbit....... ; break;
  }
}
```
